version: "3"

services:
  web:
    image: liujie/pytest:1.0
    command: ['python', '/code/app.py']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
      - "5555:80"
    networks:
      - webnet

  redis:
    image: redis
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "6379"
    networks:
      - webnet

networks:
  webnet:
