version: "3"

services:
  web:
    image: liujie/pytest:1.0
    command: ['python', '/code/app.py']
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
        constraints: [node.role == worker]
    networks:
      - external
      - internal
    ports:
      - 5555:80

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
        #constraints: [node.role == worker]
    networks:
      - internal

networks:
  external:
  internal:
    
